services:
  sonic-agent:
#   {% if manager.machine not in ("arm64", "aarch64") %}
    image: sonicorg/sonic-agent-linux:{{ SONIC_TAG }}
#   {% else %}
    image: iceblacktea/sonic-agent-linux-arm64:{{ SONIC_TAG }}
#   {% endif %}
    environment:
      - SONIC_SERVER_HOST={{ SONIC_SERVER_HOST }}
      - SONIC_SERVER_PORT={{ SONIC_SERVER_PORT }}
      - AGENT_HOST={{ SONIC_AGENT_HOST }}
      - AGENT_PORT={{ SONIC_AGENT_PORT }}
      - AGENT_KEY={{ SONIC_AGENT_KEY }}
      - ANDROID_ENABLE={{ "true" if SONIC_AGENT_ANDROID_ENABLE else "false" }}
      - USE_SAS=true
      - IOS_ENABLE={{ "true" if SONIC_AGENT_IOS_ENABLE else "false" }}
#     {% if SONIC_AGENT_IOS_ENABLE %}
      - WDA_BUNDLE_ID={{ WDA_BUNDLE_ID }}
#     {% endif %}
      - SGM_ENABLE=true
    network_mode: host
    privileged: true
    volumes:
      - '/dev/bus/usb:/dev/bus/usb'
      - '/var/lib/lockdown:/var/lib/lockdown'
      - '/var/run:/var/run'
      - '{{ (SOURCE_PATH/".android") | chown }}:/root/.android:ro'
